import { createApp } from 'vue'
import App from './App.vue'
import { TUIComponents, TUICore, genTestUserSig } from './TUIKit'

const SDKAppID = 1400799056 // Your SDKAppID
const secretKey =
  'd5aff3ebff6253ac4fe2e7fbd7d61bc42a0d4ac6c931ec4048297a3579bc9dac' //Your secretKey
const userID = '1234567890' // User ID

// init TUIKit
const TUIKit = TUICore.init({
  SDKAppID
})
// TUIKit add TUIComponents
TUIKit.use(TUIComponents)

// login TUIKit
TUIKit.login({
  userID: userID,
  userSig: genTestUserSig({
    SDKAppID,
    secretKey,
    userID
  }).userSig // The password with which the user logs in to IM. It is the ciphertext generated by encrypting information such as userID.For the detailed generation method, see Generating UserSig
})

createApp(App).use(TUIKit).mount('#app')
