import { SDKAPPID, EXPIRETIME, SECRETKEY, URSERID } from '@/config'

import { TUIComponents, TUICore, genTestUserSig } from '../TUIKit'

// init TUIKit
const TUIKit = TUICore.init({
  SDKAppID: SDKAPPID
})
// TUIKit add TUIComponents
TUIKit.use(TUIComponents)

// login TUIKit
TUIKit.login({
  userID: URSERID,
  userSig: genTestUserSig({
    SDKAppID: SDKAPPID,
    secretKey: SECRETKEY,
    userID: URSERID
  }).userSig // The password with which the user logs in to IM. It is the ciphertext generated by encrypting information such as userID.For the detailed generation method, see Generating UserSig
})

export default TUIKit
